/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Medication {
  name: string;
  dose: string;
  schedule: string;
}

export interface Attachment {
  name: string;
  type: string;
  size: string;
}

export interface Consultation {
  id: string;
  shareToken: string;
  patientName: string;
  patientAge: number;
  appointmentDate: string;
  symptoms: string;
  onsetDate: string;
  symptomNotes: string;
  medications: Medication[];
  conditions: string[];
  attachments: Attachment[];
  /** @nullable */
  voiceNote: string | null;
  createdAt: string;
}

export interface ConsultationInput {
  /** @minLength 1 */
  patientName: string;
  /** @minimum 0 */
  patientAge: number;
  appointmentDate: string;
  /** @minLength 1 */
  symptoms: string;
  onsetDate: string;
  symptomNotes: string;
  medications: Medication[];
  conditions: string[];
  attachments: Attachment[];
  /** @nullable */
  voiceNote: string | null;
}

export interface ConsultationStats {
  total: number;
  thisWeek: number;
  shared: number;
  timeSaved: string;
}

export interface ErrorResponse {
  error: string;
}

