/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List saved consultation summaries
 */
export const ListConsultationsResponseItem = zod.object({
  "id": zod.string(),
  "shareToken": zod.string(),
  "patientName": zod.string(),
  "patientAge": zod.number(),
  "appointmentDate": zod.string(),
  "symptoms": zod.string(),
  "onsetDate": zod.string(),
  "symptomNotes": zod.string(),
  "medications": zod.array(zod.object({
  "name": zod.string(),
  "dose": zod.string(),
  "schedule": zod.string()
})),
  "conditions": zod.array(zod.string()),
  "attachments": zod.array(zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "size": zod.string()
})),
  "voiceNote": zod.string().nullable(),
  "createdAt": zod.string()
})
export const ListConsultationsResponse = zod.array(ListConsultationsResponseItem)


/**
 * @summary Create a consultation summary
 */

export const createConsultationBodyPatientAgeMin = 0;




export const CreateConsultationBody = zod.object({
  "patientName": zod.string().min(1),
  "patientAge": zod.number().min(createConsultationBodyPatientAgeMin),
  "appointmentDate": zod.string(),
  "symptoms": zod.string().min(1),
  "onsetDate": zod.string(),
  "symptomNotes": zod.string(),
  "medications": zod.array(zod.object({
  "name": zod.string(),
  "dose": zod.string(),
  "schedule": zod.string()
})),
  "conditions": zod.array(zod.string()),
  "attachments": zod.array(zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "size": zod.string()
})),
  "voiceNote": zod.string().nullable()
})

export const CreateConsultationResponse = zod.object({
  "id": zod.string(),
  "shareToken": zod.string(),
  "patientName": zod.string(),
  "patientAge": zod.number(),
  "appointmentDate": zod.string(),
  "symptoms": zod.string(),
  "onsetDate": zod.string(),
  "symptomNotes": zod.string(),
  "medications": zod.array(zod.object({
  "name": zod.string(),
  "dose": zod.string(),
  "schedule": zod.string()
})),
  "conditions": zod.array(zod.string()),
  "attachments": zod.array(zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "size": zod.string()
})),
  "voiceNote": zod.string().nullable(),
  "createdAt": zod.string()
})


/**
 * @summary Get a consultation summary by id
 */
export const GetConsultationParams = zod.object({
  "id": zod.coerce.string()
})

export const GetConsultationResponse = zod.object({
  "id": zod.string(),
  "shareToken": zod.string(),
  "patientName": zod.string(),
  "patientAge": zod.number(),
  "appointmentDate": zod.string(),
  "symptoms": zod.string(),
  "onsetDate": zod.string(),
  "symptomNotes": zod.string(),
  "medications": zod.array(zod.object({
  "name": zod.string(),
  "dose": zod.string(),
  "schedule": zod.string()
})),
  "conditions": zod.array(zod.string()),
  "attachments": zod.array(zod.object({
  "name": zod.string(),
  "type": zod.string(),
  "size": zod.string()
})),
  "voiceNote": zod.string().nullable(),
  "createdAt": zod.string()
})


/**
 * @summary Get overview statistics for the consultation workspace
 */
export const GetConsultationStatsResponse = zod.object({
  "total": zod.number(),
  "thisWeek": zod.number(),
  "shared": zod.number(),
  "timeSaved": zod.string()
})


